spring:
  datasource:
    url: jdbc:mysql://cricket.c76fg1uzltxz.ap-south-1.rds.amazonaws.com/Cricket
    username: admin
    password: cricketProject
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto : update
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    username: cricketapplication61@gmail.com
    password: cricket@123
    
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          
server:
  port: 5000
  
jwtSecret: cricketAppSecretKey
jwtExpirationMs: 432000000

  