spring:
  datasource:
    url: jdbc:mysql://cricket.c76fg1uzltxz.ap-south-1.rds.amazonaws.com/Cricket
    username: admin
    password: cricketProject
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto : update
  h2:
    console:
      enabled: true
server:
  port: 5000